Repository knot-alot/knoting, pull requests merged in 2022-01, with the labels that each got.

#2 Add BGFX shader compilation
  CMakeLists.txt
  core/CMakeLists.txt
  editor/CMakeLists.txt
  res/.gitkeep
  res/CMakeLists.txt
  res/shaders/common.sh
  res/shaders/cubes/fs_cubes.sc
  res/shaders/cubes/varying.def.sc
  res/shaders/cubes/vs_cubes.sc
  third/CMakeLists.txt
  untie/CMakeLists.txt
Labels: Type: Feature

#3 Clion setup
  .gitignore
  .idea/.gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/knoting.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
Labels: Type: Enhancement

#4 untie runtime env + engine core + subsystem layout
  .idea/vcs.xml
  core/CMakeLists.txt
  core/inc/knoting/engine.h
  core/inc/knoting/window.h
  core/src/engine.cpp
  core/src/window.cpp
  untie/CMakeLists.txt
  untie/src/untie.cpp
  untie/src/untie.h
Labels: Type: Feature

#5 fix: add Logger and corresponding setup
  core/inc/knoting/log.h
  core/src/log.cpp
  untie/src/untie.cpp
Labels: Type: Bug, Type: Feature

#6 forward renderer outline
  .gitignore
  core/inc/knoting/engine.h
  core/inc/knoting/forward_renderer.h
  core/inc/knoting/window.h
  core/src/engine.cpp
  core/src/forward_renderer.cpp
  core/src/window.cpp
Labels: Type: Feature
